import {theme as themeInternal} from './theme.ts';
import type {PublicThemeType} from './PublicThemeType.ts';

export const theme = {
    fontFamily: themeInternal.fontFamily,
    fontFamilyMonospace: themeInternal.fontFamilyMonospace,
    fontSizeH1: themeInternal.fontSizeH1,
    fontSizeH2: themeInternal.fontSizeH2,
    fontSizeH3: themeInternal.fontSizeH3,
    fontSizeH4: themeInternal.fontSizeH4,
    fontSizeH5: themeInternal.fontSizeH5,
    fontSizeH6: themeInternal.fontSizeH6,
    fontSizeText: themeInternal.fontSizeText,
    fontSizeMedium: themeInternal.fontSizeMedium,
    fontSizeLarge: themeInternal.fontSizeLarge,
    fontSizeSmall: themeInternal.fontSizeSmall,
    fontWeightNormal: themeInternal.fontWeightNormal,
    fontWeightBolder: themeInternal.fontWeightBolder,
    fontWeightBold: themeInternal.fontWeightBold,
    textColor: themeInternal.textColor,
    background000: themeInternal.background000,
    background100: themeInternal.background100,
    background200: themeInternal.background200,
    background300: themeInternal.background300,
    background400: themeInternal.background400,
    background500: themeInternal.background500,
    background600: themeInternal.background600,
    colorDo: themeInternal.colorDo,
    colorRe: themeInternal.colorRe,
    colorMi: themeInternal.colorMi,
    colorFa: themeInternal.colorFa,
    colorSol: themeInternal.colorSol,
    colorLa: themeInternal.colorLa,
    colorError: themeInternal.colorError,
    colorWarning: themeInternal.colorWarning,
    colorSuccess: themeInternal.colorSuccess,
    colorAction: themeInternal.colorAction,
} as PublicThemeType;
