name: Unit & UI tests
on:
  pull_request:
    branches: [ master, beta ]

concurrency:
  group: "checks-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  unit-tests:
    name: 'Unit tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.61.1-noble

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Read .nvmrc
        run: echo "NVMRC=$(cat .nvmrc)" >> $GITHUB_ENV
        id: nvm

      - name: Use Node.js ${{ env.NVMRC }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NVMRC }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v5
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Test Unit
        run: pnpm run test --reporter=github-actions
